
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'dracula/vim',{'name':'dracula'}

call vundle#end()
filetype plugin indent on

set packpath=~/.vim/bundle/
" packadd! dracula

" set compatibility to Vim only
set nocompatible

" turn on syntax highlighting
syntax on

" turn of modelines (since I don't know how to use them)
set modelines=0

" wrap text beyond screen length
set wrap

" setting text width and similar things
set textwidth=80
set tabstop=4 " sets tabbing in general to 4 spaces
set shiftwidth=4 " sets tabbing size for C-like languages
set softtabstop=4
set expandtab " tabs become spaces
set noshiftround
set autoindent "self explanatory

" speed up scrolling
set ttyfast

" status bar
set showmode
set showcmd

"highlight matching pairs of brackets. press % to jump between them
set matchpairs+=<:>

"show line numbers
set number

" set colorscheme
colorscheme dracula
